sonar.projectKey=vallegrande-proyects_as241s5-aej-29-fe
sonar.organization=vallegrande-proyects

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**
sonar.sourceEncoding=UTF-8
sonar.typescript.lcov.reportPaths=coverage/lcov.info
